<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsTestProject>true</IsTestProject><IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <ProjectReference Include="../../src/PackageGateway.Storage/PackageGateway.Storage.csproj" />
        <ProjectReference Include="../../src/PackageGateway.Infrastructure/PackageGateway.Infrastructure.csproj" />
        <ProjectReference Include="../../src/PackageGateway.Security/PackageGateway.Security.csproj" />
        <ProjectReference Include="..\..\src\PackageGateway.Api\PackageGateway.csproj" />
        <ProjectReference Include="../../src/PackageGateway.Storage.Sqlite/PackageGateway.Storage.Sqlite.csproj" />
        <ProjectReference Include="../../src/PackageGateway.Storage.SqlServer/PackageGateway.Storage.SqlServer.csproj" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>