# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2025

SHELL ["powershell", "-NoLogo", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
ARG APP_VERSION=1.0.0
LABEL org.opencontainers.image.title="Secure Package Gateway" `
      org.opencontainers.image.description="Secure Package Gateway for Windows Server Core LTSC 2025" `
      org.opencontainers.image.version=${APP_VERSION}

RUN New-Item -ItemType Directory -Force C:\app, C:\data, C:\temp\packagegateway | Out-Null; `
    icacls C:\data /grant '*S-1-5-20:(OI)(CI)F' /T | Out-Null; `
    icacls C:\temp\packagegateway /grant '*S-1-5-20:(OI)(CI)F' /T | Out-Null

WORKDIR C:\app
COPY .container/windows/secure-package-gateway/ .
USER "NT AUTHORITY\NETWORK SERVICE"
ENV ASPNETCORE_URLS=http://+:8080 `
    DOTNET_EnableDiagnostics=0 `
    Database__Provider=Sqlite `
    Database__ConnectionString="Data Source=C:\data\packagegateway.db" `
    BlobStorage__Path=C:\data\blobs `
    Authentication__DataProtectionKeysPath=C:\data\dataprotection-keys `
    TMP=C:\temp\packagegateway `
    TEMP=C:\temp\packagegateway
VOLUME ["C:\\data"]
EXPOSE 8080
ENTRYPOINT ["C:\\app\\PackageGateway.exe"]
