<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/PackageGateway.Protocols.Npm/PackageGateway.Protocols.Npm.csproj" /><ProjectReference Include="../PackageGateway.ProtocolTests.Common/PackageGateway.ProtocolTests.Common.csproj" /><PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="xunit.v3" /><PackageReference Include="xunit.runner.visualstudio">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference></ItemGroup>
</Project>
