<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../PackageGateway.Domain/PackageGateway.Domain.csproj" />
    <ProjectReference Include="../PackageGateway.Application/PackageGateway.Application.csproj" />
    <ProjectReference Include="../PackageGateway.Security/PackageGateway.Security.csproj" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
  </ItemGroup>
</Project>
