<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../PackageGateway.Domain/PackageGateway.Domain.csproj" />
    <ProjectReference Include="../PackageGateway.Application/PackageGateway.Application.csproj" />
    <PackageReference Include="NuGet.Packaging" />
  </ItemGroup>
</Project>
